-- Complex SQL Queries for Task Management System

-- 1. Get tasks created in the last week with user statistics
SELECT 
    T.TASKID,
    T.TITLE,
    T.STATUS,
    T.CREATEDBY,
    T.CREATEDAT,
    COUNT(T2.TASKID) OVER (PARTITION BY T.CREATEDBY) AS TOTAL_TASKS_BY_USER,
    COUNT(CASE WHEN T2.STATUS = 'Done' THEN 1 END) OVER (PARTITION BY T.CREATEDBY) AS COMPLETED_TASKS_BY_USER
FROM TASKS T
LEFT JOIN TASKS T2 ON T.CREATEDBY = T2.CREATEDBY
WHERE T.CREATEDAT >= DATEADD(-7 DAY TO CURRENT_DATE)
ORDER BY T.CREATEDAT DESC;

-- 2. Get task count by status with percentage distribution
WITH StatusCounts AS (
    SELECT 
        STATUS,
        COUNT(*) AS TASK_COUNT,
        SUM(COUNT(*)) OVER() AS TOTAL_TASKS
    FROM TASKS
    GROUP BY STATUS
)
SELECT 
    STATUS,
    TASK_COUNT,
    CAST(TASK_COUNT * 100.0 / TOTAL_TASKS AS DECIMAL(5,2)) AS PERCENTAGE
FROM StatusCounts
ORDER BY 
    CASE STATUS
        WHEN 'To Do' THEN 1
        WHEN 'In Progress' THEN 2
        WHEN 'Done' THEN 3
    END;

-- 3. Get user productivity report (tasks created vs completed)
WITH UserStats AS (
    SELECT 
        CREATEDBY AS USER_ID,
        COUNT(*) AS CREATED_TASKS,
        SUM(CASE WHEN STATUS = 'Done' THEN 1 ELSE 0 END) AS COMPLETED_TASKS,
        SUM(CASE WHEN STATUS = 'In Progress' THEN 1 ELSE 0 END) AS IN_PROGRESS_TASKS,
        SUM(CASE WHEN STATUS = 'To Do' THEN 1 ELSE 0 END) AS TODO_TASKS
    FROM TASKS
    GROUP BY CREATEDBY
)
SELECT 
    USER_ID,
    CREATED_TASKS,
    COMPLETED_TASKS,
    IN_PROGRESS_TASKS,
    TODO_TASKS,
    CAST(COMPLETED_TASKS * 100.0 / NULLIF(CREATED_TASKS, 0) AS DECIMAL(5,2)) AS COMPLETION_RATE
FROM UserStats
ORDER BY COMPLETION_RATE DESC;

-- 4. Get tasks with assignment details and time spent in each status
SELECT 
    T.TASKID,
    T.TITLE,
    T.STATUS,
    T.CREATEDBY AS CREATOR_ID,
    T.ASSIGNEDTO AS ASSIGNEE_ID,
    T.CREATEDAT,
    T.UPDATEDAT,
    DATEDIFF(DAY, T.CREATEDAT, COALESCE(T.UPDATEDAT, CURRENT_TIMESTAMP)) AS DAYS_SINCE_CREATION,
    CASE 
        WHEN T.STATUS = 'Done' THEN DATEDIFF(DAY, T.CREATEDAT, T.UPDATEDAT)
        ELSE NULL
    END AS DAYS_TO_COMPLETE
FROM TASKS T
ORDER BY T.CREATEDAT DESC;

-- 5. Get workload distribution (unassigned vs assigned tasks)
SELECT 
    CASE 
        WHEN ASSIGNEDTO IS NULL THEN 'Unassigned'
        ELSE 'Assigned'
    END AS ASSIGNMENT_STATUS,
    COUNT(*) AS TASK_COUNT,
    LIST(TITLE, ', ') AS TASK_TITLES
FROM TASKS
WHERE STATUS != 'Done'
GROUP BY 
    CASE 
        WHEN ASSIGNEDTO IS NULL THEN 'Unassigned'
        ELSE 'Assigned'
    END;

-- 6. Get tasks that haven't been updated in more than 3 days (stale tasks)
SELECT 
    TASKID,
    TITLE,
    STATUS,
    CREATEDBY,
    ASSIGNEDTO,
    CREATEDAT,
    UPDATEDAT,
    DATEDIFF(DAY, COALESCE(UPDATEDAT, CREATEDAT), CURRENT_TIMESTAMP) AS DAYS_STALE
FROM TASKS
WHERE STATUS != 'Done'
  AND DATEDIFF(DAY, COALESCE(UPDATEDAT, CREATEDAT), CURRENT_TIMESTAMP) > 3
ORDER BY DAYS_STALE DESC;

-- 7. Get monthly task creation trend
SELECT 
    EXTRACT(YEAR FROM CREATEDAT) AS YEAR,
    EXTRACT(MONTH FROM CREATEDAT) AS MONTH,
    COUNT(*) AS TASKS_CREATED,
    SUM(CASE WHEN STATUS = 'Done' THEN 1 ELSE 0 END) AS TASKS_COMPLETED
FROM TASKS
GROUP BY 
    EXTRACT(YEAR FROM CREATEDAT),
    EXTRACT(MONTH FROM CREATEDAT)
ORDER BY YEAR DESC, MONTH DESC;

-- 8. Get top performers (users who completed most tasks)
SELECT 
    ASSIGNEDTO AS USER_ID,
    COUNT(*) AS COMPLETED_TASKS,
    MIN(CREATEDAT) AS FIRST_TASK_DATE,
    MAX(UPDATEDAT) AS LAST_COMPLETION_DATE,
    AVG(DATEDIFF(DAY, CREATEDAT, UPDATEDAT)) AS AVG_DAYS_TO_COMPLETE
FROM TASKS
WHERE STATUS = 'Done' 
  AND ASSIGNEDTO IS NOT NULL
GROUP BY ASSIGNEDTO
HAVING COUNT(*) > 0
ORDER BY COMPLETED_TASKS DESC;

-- 9. Get task dependencies (tasks created by same user in sequence)
SELECT 
    T1.TASKID AS TASK_ID,
    T1.TITLE AS TASK_TITLE,
    T1.STATUS AS TASK_STATUS,
    T2.TASKID AS NEXT_TASK_ID,
    T2.TITLE AS NEXT_TASK_TITLE,
    T2.STATUS AS NEXT_TASK_STATUS,
    DATEDIFF(MINUTE, T1.CREATEDAT, T2.CREATEDAT) AS MINUTES_BETWEEN
FROM TASKS T1
INNER JOIN TASKS T2 ON T1.CREATEDBY = T2.CREATEDBY 
                    AND T2.CREATEDAT > T1.CREATEDAT
WHERE DATEDIFF(HOUR, T1.CREATEDAT, T2.CREATEDAT) < 24
ORDER BY T1.CREATEDAT, T2.CREATEDAT;

-- 10. Get comprehensive task report with ranking
SELECT 
    TASKID,
    TITLE,
    STATUS,
    CREATEDBY,
    ASSIGNEDTO,
    CREATEDAT,
    UPDATEDAT,
    DENSE_RANK() OVER (ORDER BY CREATEDAT DESC) AS CREATION_RANK,
    ROW_NUMBER() OVER (PARTITION BY STATUS ORDER BY CREATEDAT) AS STATUS_RANK,
    FIRST_VALUE(TITLE) OVER (PARTITION BY CREATEDBY ORDER BY CREATEDAT) AS FIRST_TASK_BY_USER,
    LAST_VALUE(TITLE) OVER (PARTITION BY CREATEDBY ORDER BY CREATEDAT ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_TASK_BY_USER
FROM TASKS
ORDER BY CREATEDAT DESC;


