-- Create Database (run this in isql or another Firebird tool)
-- CREATE DATABASE 'TaskDB.fdb' USER 'SYSDBA' PASSWORD 'masterkey' PAGE_SIZE 16384 DEFAULT CHARACTER SET UTF8;

-- Create Tasks table
CREATE TABLE TASKS (
    TASKID INTEGER NOT NULL PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('To Do', 'In Progress', 'Done')),
    CREATEDBY INTEGER NOT NULL,
    ASSIGNEDTO INTEGER,
    CREATEDAT TIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP
);

-- Create generator for auto-increment
CREATE GENERATOR GEN_TASK_ID;
SET GENERATOR GEN_TASK_ID TO 0;

-- Create trigger for auto-increment
SET TERM ^ ;
CREATE TRIGGER BI_TASKS FOR TASKS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.TASKID IS NULL OR NEW.TASKID = 0) THEN
    NEW.TASKID = GEN_ID(GEN_TASK_ID, 1);
END^
SET TERM ; ^

-- Create indexes for better performance
CREATE INDEX IDX_TASKS_STATUS ON TASKS(STATUS);
CREATE INDEX IDX_TASKS_CREATEDBY ON TASKS(CREATEDBY);
CREATE INDEX IDX_TASKS_ASSIGNEDTO ON TASKS(ASSIGNEDTO);
CREATE INDEX IDX_TASKS_CREATEDAT ON TASKS(CREATEDAT);

-- Insert sample data
INSERT INTO TASKS (TITLE, DESCRIPTION, STATUS, CREATEDBY, ASSIGNEDTO, CREATEDAT) 
VALUES ('Setup project structure', 'Initialize new project with proper folder structure', 'Done', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO TASKS (TITLE, DESCRIPTION, STATUS, CREATEDBY, ASSIGNEDTO, CREATEDAT) 
VALUES ('Implement authentication', 'Add JWT authentication to the API', 'In Progress', 1, 2, CURRENT_TIMESTAMP);

INSERT INTO TASKS (TITLE, DESCRIPTION, STATUS, CREATEDBY, ASSIGNEDTO, CREATEDAT) 
VALUES ('Create unit tests', 'Write unit tests for all services', 'To Do', 2, NULL, CURRENT_TIMESTAMP);

INSERT INTO TASKS (TITLE, DESCRIPTION, STATUS, CREATEDBY, ASSIGNEDTO, CREATEDAT) 
VALUES ('Setup CI/CD pipeline', 'Configure GitHub Actions for automated deployment', 'To Do', 1, 3, CURRENT_TIMESTAMP);

INSERT INTO TASKS (TITLE, DESCRIPTION, STATUS, CREATEDBY, ASSIGNEDTO, CREATEDAT) 
VALUES ('Database optimization', 'Optimize database queries for better performance', 'In Progress', 3, 3, CURRENT_TIMESTAMP);

COMMIT;


